### ISSUE TITLE
GFCS Margin Loss Bug

### ISSUE THREAD

**Issue by nicklordox** [CSIPlab/BASES#1]
The margin loss implementation in the GFCS mirror (./comparison/GFCS
/gfcs_util.py) has inherited a bug from the original GFCS repo. See the change made to margin_loss in https://github.com/fiveai/GFCS/blob/main/gfcs_util.py .

This will apply to both margin_loss and margin_loss_v2 in this repo. GFCS's reproduced untargeted attack results will improve somewhat on the application of this patch. (This does not affect the results reported in the GFCS paper itself.)

**Comment by zikuicai** [comment]
Sorry for the long delay! I have updated the repo.
